version: '3.8'

services:
  server1:
    build: ./server
    container_name: backend_server1
    environment:
      - SERVER_NAME=Server1
      - SERVER_PORT=80
    ports:
      - "8081:80"    # 添加端口映射
    networks:
      lb_network:
        ipv4_address: 172.20.0.11

  server2:
    build: ./server
    container_name: backend_server2
    environment:
      - SERVER_NAME=Server2
      - SERVER_PORT=80
    ports:
      - "8082:80"    # 添加端口映射
    networks:
      lb_network:
        ipv4_address: 172.20.0.12

  server3:
    build: ./server
    container_name: backend_server3
    environment:
      - SERVER_NAME=Server3
      - SERVER_PORT=80
    ports:
      - "8083:80"    # 添加端口映射
    networks:
      lb_network:
        ipv4_address: 172.20.0.13

networks:
  lb_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16